#!/usr/bin/env python3
"""Render coverletter.txt to coverletter.docx for the PLOS ONE File Inventory.

PLOS ONE's technical check on the 2026-08-24 submission returned:

    "We notice that your Cover Letter in File Inventory are in Note pad.
     Please upload Cover Letter in File Inventory in word format."

so the uploaded cover letter must be a .docx. The .txt beside this script stays
the source of record; this file exists so that the .docx has a producer rather
than being made once by hand and never the same way again.

Why that matters here specifically: NO GATE READS EITHER FILE. `coverletter.txt`
is untracked and ignored by .gitignore's `cover*letter*.txt`, and the .docx is
covered by `docs/submission/plosone/*.docx`. Neither appears in `git status`,
neither is in `reproduce/MANUSCRIPT_MD5`, and `validate.py` reads only artifacts
under output/ and analysis/. If the .txt is edited and the .docx regenerated by
some other method, the submitted document can differ from its source and nothing
in the repository is able to notice. The round-trip assertion below is the whole
value of this script; it is not decoration and must not be removed.

FORMAT CONVERSION ONLY. One .txt line becomes one .docx paragraph, blank lines
included as empty paragraphs, so that "\n".join(paragraph texts) reproduces the
source exactly. Nothing is rewrapped, reflowed or reworded. The typeface is set
to Times New Roman 12pt to match the submission manuscript, since the two are
read together; that is formatting and touches no character of the text.

REPRODUCIBILITY. The output is content-reproducible and NOT byte-reproducible:
two builds of the same source differ. The cause is the ZIP member timestamps in
the local file headers, stamped at save. It is *not* a moving creation timestamp
-- `dcterms:created` and `dcterms:modified` are fixed at 2013-12-23T23:15:00Z,
inherited from python-docx's shipped default.docx, in this file and in the
manuscript DOCX alike. Measured at dispatch 70, where two consecutive builds
returned the same md5 and a third after a two-second pause did not: a
reproducibility test that runs faster than the resolution of the clock it is
testing will confirm itself. Any such test here needs a pause of more than one
second between builds.

Consequently the .docx md5 is not a pin and must not be recorded as one. Do not
rebuild an already-uploaded cover letter to "refresh" it: the bytes would move
for no reason and the uploaded file would no longer match the recorded one.

Usage:  python build_coverletter_docx.py [SOURCE.txt] [OUTPUT.docx]

Requires python-docx (declared in pyproject.toml's [dev] and [lock] extras).
"""

import sys
from pathlib import Path

try:
    from docx import Document
    from docx.shared import Pt
except ImportError as exc:  # pragma: no cover - dependency is declared
    sys.exit("ERROR: python-docx is required (pip install 'python-docx>=1.1'): %s" % exc)


HERE = Path(__file__).resolve().parent
DEFAULT_SOURCE = HERE / "coverletter.txt"
DEFAULT_OUTPUT = HERE / "coverletter.docx"

FONT_NAME = "Times New Roman"
FONT_SIZE_PT = 12


def read_lines(source):
    """The source lines, with only the terminating newline dropped."""
    if not source.is_file():
        sys.exit("ERROR: cover letter source missing: %s" % source)
    lines = source.read_text(encoding="utf-8").split("\n")
    if lines and lines[-1] == "":
        lines.pop()
    return lines


def build(lines, output):
    document = Document()
    normal = document.styles["Normal"]
    normal.font.name = FONT_NAME
    normal.font.size = Pt(FONT_SIZE_PT)
    normal.paragraph_format.space_after = Pt(0)
    for line in lines:
        document.add_paragraph(line)
    output.parent.mkdir(parents=True, exist_ok=True)
    document.save(str(output))


def verify(lines, output):
    """Re-open the written file and require the text to be unchanged.

    This is the assertion the script exists for. A cover letter whose .docx has
    silently drifted from its .txt is exactly the failure no gate here can see.
    """
    reopened = Document(str(output))
    extracted = "\n".join(p.text for p in reopened.paragraphs)
    source = "\n".join(lines)
    if extracted != source:
        sys.exit(
            "ERROR: the written .docx does not extract back to its source.\n"
            "  source    %d chars, %d lines\n"
            "  extracted %d chars, %d paragraphs"
            % (len(source), len(lines), len(extracted), len(reopened.paragraphs))
        )
    return reopened, extracted


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    source = Path(argv[0]) if len(argv) > 0 else DEFAULT_SOURCE
    output = Path(argv[1]) if len(argv) > 1 else DEFAULT_OUTPUT

    lines = read_lines(source)
    build(lines, output)
    reopened, extracted = verify(lines, output)

    print("SOURCE  %s" % source)
    print("  lines                   %d" % len(lines))
    print("  words (str.split)       %d" % len(extracted.split()))
    print("  characters              %d" % len(extracted))
    print()
    print("OUTPUT  %s" % output)
    print("  paragraphs              %d" % len(reopened.paragraphs))
    print("  font                    %s %dpt" % (FONT_NAME, FONT_SIZE_PT))
    print("  bytes                   %d" % output.stat().st_size)
    print("  round trip              extracted == source")
    print()
    print("OK  %s" % output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
